package com.ochwada.learnify.motivation.model;


import jakarta.persistence.*;
import lombok.*;

/**
 * *******************************************************
 * Package: com.ochwada.learnify.motivation.model
 * File: Quote.java
 * Author: Ochwada
 * Date: Monday, 28.Jul.2025, 5:42 PM
 * Description: Represents a motivational quote entity stored in the database.
 * *******************************************************
 */


/**
 * This class is mapped to the "motivations" table.
 * *
 * It uses Lombok annotations to generate boilerplate code:
 * - {@code @Data} generates getters, setters, toString, equals, and hashCode.
 * - {@code @NoArgsConstructor} creates a no-argument constructor.
 * - {@code @AllArgsConstructor} creates a constructor with all fields.
 * - {@code @Builder} enables the builder pattern for Quote creation.
 */
@Entity
@Table(name = "motivations")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Quote {
    /**
     * The unique identifier for the quote.
     * It is the primary key and is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The content of the motivational quote.
     * This field is required and cannot be null.
     */
    @Column(nullable = false)
    private String text;

    /**
     * The author of the quote.
     * This field is optional.
     */
    @Column
    private String author;
}
